# Generated by Django 3.1.7 on 2021-03-17 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0006_auto_20210317_1616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuts', models.CharField(choices=[('OK', 'Ok'), ('HS', 'NON_FUNCTIONTAL'), ('LS', 'LOOSE')], default='OK', max_length=2)),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.asset')),
                ('inventorist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to='inventory.inventorysession')),
            ],
        ),
    ]
