# Generated by Django 3.1.7 on 2021-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_merge_20210317_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='picture',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
